name: NodeJS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
    - uses: egor-tensin/setup-clang@v1.4
    - run: bun install
    - run: bun type
    - run: bun test
